### ISSUE TITLE
WIREFRAME: Form 3X Header

### ISSUE THREAD

**Issue by MitchellTCG** [fecgov/fecfile-project-management#42]
### Business Reason ### 

As an Admin, I will be able to create Form 3X header information that I can save and update

Wireframe
should show information found on lines 1-5 of Form 3X

**Comment by MitchellTCG** [comment]
Here is a copy of the "Creating a Form 3X" Workflow:
![Creating NEW Reports Workflow.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d4f6e727-e6d0-41e8-b487-e2740fc14b0a)

**Comment by MitchellTCG** [comment]
Here is the initial Wireframe:
![Initial State of Creating a Report.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8eac41d0-0985-48f8-9df3-f9b4f10bc4a5)

Wire Prototype Videos for:

1. Update address
https://images.zenhubusercontent.com/417265237/c58ebe4c-86d2-4d3c-9c4d-6a9d20059a3e/update_address.mp4
2. Going to form 1
https://images.zenhubusercontent.com/417265237/3540d89a-1a11-4590-9126-539013c1a086/going_to_form_1.mp4
3. Memo Box
https://images.zenhubusercontent.com/417265237/a0d56d8d-cb05-495e-8693-ebd28a5f1617/memo_box.mp4
4. Multicandidate Tooltip
https://images.zenhubusercontent.com/417265237/a0588b49-a89d-4650-af7b-fdfb14f818dc/multicandidate_tooltip.mp4

**Comment by MitchellTCG** [comment]
Wire Prototype Videos for:

Update address

**Comment by MitchellTCG** [comment]
Here are more individual Wireframes:

Update Address error messages:
![Update Address Error Messages.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/0d55a46b-41d7-47a5-962d-a9f90370513f)

Memo box error message:
![Memo box error message.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8a013644-3cb1-43ea-aa95-4f4aecc63b63)

Multicandidate Tooltip:
![Multicandidate Tooltip.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/4adf39a0-92d2-4a62-9c13-bba48ef1981b)

**Comment by JonellaCulmer** [comment]
@MitchellTCG 

For the address change:
- I'm curious about what happens when someone no longer wants to change their address. Does unchecking just revert back to what it was? 
- And I'm assuming the errors are really only in the case that someone edits a field and it is now blank, otherwise anything entered will work. 

For the multicandidate tooltip:
- We have never included links inside the tooltips, so I'm interested in observing how people interact with them - particularly with the link inside the tooltip.
- Also, can we change the formatting of the link to say "Learn more about multicandidate committee status".
- I'm also concerned about relying on conveying links with just the color change. Would also like links to be underlined. Our pattern has been a dotted line but I think you've used a solid line in at least one place. We just need to pick one format for links in fecfile and it should include some kind of underline.

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg @AureliaKhorsand 

Here are updated videos for create a report starting with Type of Report

https://images.zenhubusercontent.com/417265237/9d863d7f-e042-4238-b03f-def1f93d5050/fec_form_3x_monthly.mp4

https://images.zenhubusercontent.com/417265237/d93aed37-59e3-4ec7-8623-d8682abbc425/fec_form_3x_quarterly.mp4

https://images.zenhubusercontent.com/417265237/da684e62-d273-4246-8084-931d9bedb9d8/fec_form_3x_12_daypre.mp4

https://images.zenhubusercontent.com/417265237/373e8b7e-88f7-4865-b05b-b2ee9cf5395c/fec_form_3x_30_daypost.mp4

https://images.zenhubusercontent.com/417265237/087f85b1-d9a9-465e-b386-f7fea2ecffe4/fec_form_3x_termination.mp4

**Comment by MitchellTCG** [comment]
@JonellaCulmer @mary-tcg @AureliaKhorsand 

five wires for the different Types of Reports:
![Monthly report save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/1631c55b-bd0c-4628-9405-4ff5399b6f33)

![Quarterly report save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/d57d8e8d-6b7e-435b-9b3f-7fdf6522facf)

![12-Day Pre-Election Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/dbd287a7-990f-4c6d-9380-b99304646817)

![30-Day Post-Election Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/191af861-dffa-4154-873e-0eb69d66fc75)

![Termination Save.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/2c40de79-1516-48cd-94e2-c02dd0537c07)
